"""
You are given two strings s and t. String t is generated by randomly shuffling string s and then adding one more letter at a random position. Return the letter that was added to t.

Examples
find_the_difference("abcd", "abcde") ➞ "e"

find_the_difference("", "y") ➞ "y"

find_the_difference("ae", "aea") ➞ "a"
"""

from collections import Counter

def find_the_difference(s, t):

    return (Counter(t) - Counter(s)).most_common()[0][0]
    # for _ in range(100):
    #     s_lst = [chr(randint(97, 122)) for _ in range(randint(100, 10000))]
    #     t_lst = s_lst.copy()
    #     add_on = chr(randint(97, 122))
    #     shuffle(t_lst)
    #     t_lst.insert(randint(0, len(s_lst) - 1), add_on)
    #     shuffle(t_lst)
    #
    # return find_the_difference("".join(s_lst), "".join(t_lst))



print(find_the_difference("abcd", "abcde"))
print(find_the_difference("", "y"))
print(find_the_difference("ae", "aea"))

